Reading Data from Diffrent Sources

In [1]:
import pandas as pd
from io import StringIO

In [8]:
Data='{ "name":"Kajal", "email":"kajal@gmail.com", "job_profile": [{"Title":"Team Lead","Salary":20000 }] }'
df=pd.read_json(StringIO(Data))

In [9]:
df

    name            email                              job_profile
0  Kajal  kajal@gmail.com  {'Title': 'Team Lead', 'Salary': 20000}

In [ ]:
df.to_json()

## here the default parameter is orient here which id by defaut indec the o is the index of the records
#  similar to the 
# df.to_json(orient='index')

'{"0":{"name":"Kajal","email":"kajal@gmail.com","job_profile":{"Title":"Team Lead","Salary":20000}}}'

In [12]:
df.to_json(orient='records')

'[{"name":"Kajal","email":"kajal@gmail.com","job_profile":{"Title":"Team Lead","Salary":20000}}]'

In [16]:
df.to_json(orient='values')

'[["Kajal","kajal@gmail.com",{"Title":"Team Lead","Salary":20000}]]'

In [20]:
####### Reading from CSV

df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",header=None)
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [21]:
df.to_csv("iris.csv")